package mobile
package mobile







































































































































































































































































}	return "SilverBullet Mobile"func GetVersion() string {// GetVersion returns the SilverBullet version}	}		}			log.Printf("Could not write config page: %v", err)		if _, err := rootSpaceConfig.SpacePrimitives.WriteFile(configPagePath, configContent, nil); err != nil {		configContent := []byte("# Configuration\n\nThis is your configuration page.\n")		log.Printf("Config page %s does not exist, creating...", configPagePath)	if err == server.ErrNotFound {	_, err = rootSpaceConfig.SpacePrimitives.GetFileMeta(configPagePath)	configPagePath := "CONFIG.md"	// Config page	}		}			log.Printf("Could not write index page: %v", err)		if _, err := rootSpaceConfig.SpacePrimitives.WriteFile(indexPagePath, indexContent, nil); err != nil {		indexContent := []byte("# Welcome to SilverBullet\n\nThis is your personal knowledge base.\n")		log.Printf("Index page %s does not exist, creating...", indexPagePath)	if err == server.ErrNotFound {	_, err := rootSpaceConfig.SpacePrimitives.GetFileMeta(indexPagePath)	indexPagePath := fmt.Sprintf("%s.md", rootSpaceConfig.IndexPage)	// Index pagefunc ensureIndexAndConfig(rootSpaceConfig *server.SpaceConfig) {// ensureIndexAndConfig ensures index and config pages exist}	return globalServer.IsRunning()	}		return false	if globalServer == nil {func IsServerRunning() bool {// IsServerRunning returns whether a server is currently running}	return globalServer.GetURL()	}		return ""	if globalServer == nil {func GetServerURL() string {// GetServerURL returns the URL of the running server}	return err	globalServer = nil	err := globalServer.Stop()	}		return nil	if globalServer == nil {func StopServer() error {// StopServer stops the currently running server}	return nil	globalServer = srv	}		return err	if err := srv.Start(spaceFolderPath); err != nil {	}		return err	if err != nil {	srv, err := NewServer(spaceFolderPath, port)	}		return fmt.Errorf("server is already running")	if globalServer != nil && globalServer.IsRunning() {func StartServer(spaceFolderPath string, port int) error {// It starts a server with the given space folder path and port// StartServer is a convenience function for Go Mobile binding}	return ""	}		return fmt.Sprintf("http://127.0.0.1:%d", s.config.Port)	if s.config != nil {	defer s.mu.Unlock()	s.mu.Lock()func (s *Server) GetURL() string {// GetURL returns the URL where the server is accessible}	return s.running	defer s.mu.Unlock()	s.mu.Lock()func (s *Server) IsRunning() bool {// IsRunning returns whether the server is currently running}	return nil	log.Println("SilverBullet server stopped")	s.running = false	s.wg.Wait()	}		}			return err			log.Printf("Server shutdown error: %v", err)		if err := s.httpServer.Shutdown(ctx); err != nil {		defer cancel()		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)	if s.httpServer != nil {	}		s.cancel()	if s.cancel != nil {	log.Println("Stopping SilverBullet server...")	}		return nil	if !s.running {	defer s.mu.Unlock()	s.mu.Lock()func (s *Server) Stop() error {// Stop stops the SilverBullet server}	return nil	s.running = true	}()		}			log.Printf("HTTP server error: %v", err)		if err := s.httpServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {		log.Printf("Starting SilverBullet server on http://127.0.0.1:%d", serverConfig.Port)		defer s.wg.Done()	go func() {	s.wg.Add(1)	s.cancel = cancel	ctx, cancel := context.WithCancel(context.Background())	// Start server in background	s.config = serverConfig	}		Handler: r,		Addr:    fmt.Sprintf("%s:%d", serverConfig.BindHost, serverConfig.Port),	s.httpServer = &http.Server{	// Create HTTP server	r := server.Router(serverConfig)	// Create the router	ensureIndexAndConfig(rootSpaceConfig)	// Ensure index and config pages exist	rootSpaceConfig.ShellBackend = server.NewNotSupportedShell()	// Disable shell backend for mobile	)		spacePrimitives,		bundlePathDate,		"base_fs",		client_bundle.BundledFiles,	rootSpaceConfig.SpacePrimitives = server.NewReadOnlyFallthroughSpacePrimitives(	)		nil,		bundlePathDate,		"client",		client_bundle.BundledFiles,	serverConfig.ClientBundle = server.NewReadOnlyFallthroughSpacePrimitives(	bundlePathDate := time.Now()	// Extract the last modified time from the main binary	}		return fmt.Errorf("failed to create space primitives: %w", err)	if err != nil {	spacePrimitives, err := server.NewDiskSpacePrimitives(rootSpaceConfig.SpaceFolderPath, "")	// Set up space primitives	}		return rootSpaceConfig, nil	serverConfig.SpaceConfigResolver = func(r *http.Request) (*server.SpaceConfig, error) {	// Simple space config resolver	}		ReadOnlyMode:     false,		SpaceFolderPath:  spaceFolderPath,		SpaceDescription: "Powerful and programmable note taking app",		SpaceName:        "SilverBullet",		IndexPage:        "index",	rootSpaceConfig := &server.SpaceConfig{	}		Port:     s.config.Port,		BindHost: "127.0.0.1",	serverConfig := &server.ServerConfig{	// Build the server configuration	}		return fmt.Errorf("server is already running")	if s.running {	defer s.mu.Unlock()	s.mu.Lock()func (s *Server) Start(spaceFolderPath string) error {// Start starts the SilverBullet server}	}, nil		running: false,		},			Port:     port,			BindHost: "127.0.0.1",		config: &server.ServerConfig{	return &Server{	}		port = 3000	if port <= 0 {	}		return nil, fmt.Errorf("space folder path cannot be empty")	if spaceFolderPath == "" {func NewServer(spaceFolderPath string, port int) (*Server, error) {// NewServer creates a new server instance with the given configurationvar globalServer *Server}	ReadOnly        bool	IndexPage       string	Port            int	SpaceFolderPath stringtype Config struct {// Config holds the configuration for starting the server}	running    bool	mu         sync.Mutex	wg         sync.WaitGroup	cancel     context.CancelFunc	config     *server.ServerConfig	httpServer *http.Servertype Server struct {// Server represents a running SilverBullet server instance)	"github.com/silverbulletmd/silverbullet/server"	"github.com/silverbulletmd/silverbullet/client_bundle"	"time"	"sync"	"os"	"net/http"	"log"	"io/fs"	"fmt"	"context"import (